<mark style="font-size: 20px;"><b>INFO MICHAEL BIRKNER:<br />Hier auf der Startseite
    könnte ein Text, Bilder oder etwas anderes wie z. B. ein News-Feed stehen
    (z. B. ein OTS-Feed zu den Schlagwörtern "Arbeiterkammer" und "Gewerkschaft"
    könnte passen). Zur Veranschaulichung folgt ein Blindtext.</b></mark>

<br />
<h2>IPIS TEST</h2>

<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren,
no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>

<ul>
<li>WIFO</li>
<li>IHS</li>
<li>AK Infoservice</li>
<li>JurExpert</li>
<li>uvm.</li>
</ul>

<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero
eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea
takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet,
consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et
dolore magna aliquyam erat, sed diam voluptua.</p>

<p>At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd
gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>