<?php
  // Set page title.
  $this->headTitle($this->translate('Search Home'));

  // Disable top search box -- this page has a special layout.
  // IPIS: We enable the top search box as we use this one instead of the one below.
  //       We just need to comment out the next line to do this.
  //$this->layout()->searchbox = false;

  // Set default value if necessary:
  if (!isset($this->searchClassId)) {
    $config = $this->config()->get('config');
    $this->searchClassId = $config->Site->defaultSearchBackend ?? 'Solr';
  }

  $this->layout()->breadcrumbs = false;
?>

<?php // IPIS: Remove search box on home screen as we put it into the header
/*
<div class="searchHomeContent">
  <?php $this->slot('search-home-hero')->start() ?>
    <?=$this->context($this)->renderInContext("search/searchbox.phtml", ['ignoreHiddenFilterMemory' => true])?>
    <?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, '$("#searchForm_lookfor").focus();', 'SET'); ?>
  <?=$this->slot('search-home-hero')->end() ?>
</div>
*/
?>

<?=implode('', array_map([$this, 'contentBlock'], $blocks ?? []))?>
