<?php
  // Set page title.
  $this->headTitle($this->translate('Search Home'));

  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;

  // Set default value if necessary:
  if (!isset($this->searchClassId)) {
    $config = $this->config()->get('config');
    $this->searchClassId = $config->Site->defaultSearchBackend ?? 'Solr';
  }

  $this->layout()->breadcrumbs = false;

  $options = $this->searchOptions($this->searchClassId);
  $basicSearch = $this->searchbox()->combinedHandlersActive() ? 'combined-searchbox' : $options->getSearchAction();
?>

<div id="ipis-home-container">

    <div id="ipis-home-heading">
        <div class="ipis-logo"></div>
        <div class="ipis-text">
            <div class="ipis-hohe-bg"><span class="ipis-hohe-emph">I</span>NTERESSENS<span class="ipis-hohe-emph">P</span>OLITISCHES</div>
            <div class="ipis-hohe-bg"><span class="ipis-hohe-emph">I</span>NFORMATIONS<span class="ipis-hohe-emph">S</span>YSTEM</div>
        </div>
    </div>

    <div id="ipis-home-infotext">Publikationen zur Arbeitnehmer:innen-Vertretung finden</div>

    <div id="ipis-home-searchbox">
        <form id="searchForm" class="searchForm navbar-form navbar-left flip" method="get" action="<?=$this->url($basicSearch)?>" name="searchForm" autocomplete="off">
            <div class="ipis-searchform-conatiner">
                <input id="searchForm_lookfor" class="ipis-home-lookfor searchForm_lookfor form-control search-query<?php if($this->searchbox()->autocompleteEnabled($this->searchClassId)):?> autocomplete searcher:<?=$this->escapeHtmlAttr($this->searchClassId) ?><?=$this->searchbox()->autocompleteAutoSubmit($this->searchClassId) ? ' ac-auto-submit' : '' ?><?php endif ?>" type="text" name="lookfor" placeholder="<?=$this->transEscAttr('Search') ?> ..." aria-label="<?=$this->transEscAttr("search_terms")?>" />
                <div class="ipis-searchform-lookfor-input-group-btn">
                    <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
                </div>
            </div>
        </form>
    </div>
    
    <?=implode('', array_map([$this, 'contentBlock'], $blocks ?? []))?>

</div>