<?php foreach ($this->driver->getSummary() as $summary): ?>
  <?php $htmlContent = substr(html_entity_decode(trim($summary)), 0, 1) == '<' && substr(html_entity_decode(trim($summary)), -1) == '>'; ?>  
  <?=$htmlContent ? html_entity_decode($summary) : ($this->escapeHtml($summary) . '<br />')?>
<?php endforeach; ?>
<?php $isbn = $this->driver->getCleanISBN(); ?>
<?php foreach ($this->summaries($isbn) as $provider => $content): ?>
  <?php foreach ($content as $summary): ?>
    <?php $htmlContent = substr($summary, 0, 1) == '<' && substr($summary, -1) == '>'; ?>
    <?=$htmlContent ? $summary : ($this->escapeHtml($summary) . '<br />')?>
  <?php endforeach; ?>
<?php endforeach; ?>
